name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    container:
      image: node:14.16
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: id -a
    - run: sudo apt update && sudo apt -y install jq
