name: Touch test
on: [push, workflow_dispatch]

jobs:
  Pollute-Work-Dir:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    container:
      image: ubuntu:jammy
    steps:
    - run: ls -l
    - run: touch pollute.txt
    - run: chmod 600 pollute.txt
    - run: sudo chown root:root pollute.txt
    - run: ls -l
    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: pollute
        path: ./pollute.txt
  second-job:
    needs: Pollute-Work-Dir
    runs-on: self-hosted
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: pollute
    - run: ls -lA
