name: Touch test
on: [push, workflow_dispatch]

jobs:
  Pollute-Work-Dir:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - run: ls -l
    - run: touch pollute.txt
    - run: ls -l
  second-job:
    runs-on: self-hosted
    steps:
    - ls -lA
